version: 2
updates:
  # Veille et mises à jour des dépendances Python (pip)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(deps)"

  # Veille et mises à jour des actions GitHub
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "ci(deps)"
